name: Markdown style checks
on:
  push:
  pull_request:
  workflow_dispatch:
jobs:
  run_style_checks:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: ['3.11']
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }} on ${{ matrix.os }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install pymarkdownlnt
      - name: Lint with pymarkdown
        if: always()
        run: |
          pymarkdown scan **/*.md
