name: Python style checks
on:
  push:
  pull_request:
  workflow_dispatch:
jobs:
  run_style_checks:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: ['3.9', '3.10', '3.11']
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }} on ${{ matrix.os }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install -e .[github]
      - name: Check formatting with black
        if: always()
        run: |
          black . --check --diff
      - name: Check sorted imports with isort
        if: always()
        run: |
          isort . --check --diff
      - name: Lint with pylint
        if: always()
        run: |
          pylint . --recursive=yes
      - name: Check types with pyright
        if: always()
        run: |
          pyright
