name: Python style checks
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:
jobs:
  run_style_checks:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: ['3.9', '3.10', '3.11']
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Look out for file changes
        uses: dorny/paths-filter@v3
        id: changes
        with:
          filters: |
            py_files:
              - '**/*.py'
      - name: Set up Python ${{ matrix.python-version }} on ${{ matrix.os }}
        uses: actions/setup-python@v5
        if: steps.changes.outputs.py_files == 'true'
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        if: steps.changes.outputs.py_files == 'true'
        run: |
          python -m pip install -e .[github]
      - name: Check formatting with black
        if: steps.changes.outputs.py_files == 'true'
        run: |
          black . --check --diff
      - name: Check sorted imports with isort
        if: steps.changes.outputs.py_files == 'true'
        run: |
          isort . --check --diff
      - name: Lint with pylint
        if: steps.changes.outputs.py_files == 'true'
        run: |
          pylint . --recursive=yes
      - name: Check types with pyright
        if: steps.changes.outputs.py_files == 'true'
        run: |
          pyright
